### ISSUE TITLE
Build the Restaurant Menu Screen

### ISSUE THREAD

**Issue by VBeegle** [MobileApps-Cascadia/orca-stars-ios#14]
Def: Design the Restaurant business menu screen of the app to match the Android version. This will be filled with placeholders for the Database. (Just storyboard, no code yet)
DoD: The restaurant menu screen has been designed to be similar to the Android one, while still being distinctly iOS.
User Story: As an orca lover, I want to find businesses that focus on sustainable practices so that I avoid supporting businesses that don’t.

**Comment by JoshuaAaron** [comment]
Recent pull request and merge closes this issue as well as issue #17

**Comment by JoshuaAaron** [comment]
Recent pull request and merge closes this issue as well as issue #17
