### ISSUE TITLE
Connect Main to Restaurant Menu

### ISSUE THREAD

**Issue by VBeegle** [MobileApps-Cascadia/orca-stars-ios#15]
Def: Create code so that the Restaurant icon button leads to the Restaurant menu screen. (Very simple code for now)
DoD: The correct button is coded and works.
User Story: As an orca lover, I want to find businesses that focus on sustainable practices so that I avoid supporting businesses that don’t.

**Comment by charlesmsy** [comment]
Created RestaurantMenuViewController.swift,RestaurantMenu Scene, connected main menu to Restaurrant scene
