### ISSUE TITLE
Build the Restaurant Detail Screen

### ISSUE THREAD

**Issue by VBeegle** [MobileApps-Cascadia/orca-stars-ios#16]
Def: Design the Restaurant business details screen of the app to match the Android version. This will be filled with placeholders for the Database. (Just storyboard, no code yet)
DoD: The restaurant detail screen has been designed to be similar to the Android one, while still being distinctly iOS.
User Story: As an orca lover, I want to find businesses that focus on sustainable practices so that I avoid supporting businesses that don’t.

**Comment by JoshuaAaron** [comment]
I've started this in my previous issue (#14 ), but it needs work to be DoD.
