### ISSUE TITLE
Connect the Restaurant Menu to the Restaurant Detail

### ISSUE THREAD

**Issue by VBeegle** [MobileApps-Cascadia/orca-stars-ios#17]
Def: Create code so that the Restaurant listing selected leads to the Restaurant Detail screen. (Very simple code for now)
DoD: The correct button is coded and works.
User Story: As an orca lover, I want to find businesses that focus on sustainable practices so that I avoid supporting businesses that don’t.

**Comment by JoshuaAaron** [comment]
This was done inside of issue #14 so I'm closing this issue.
