### ISSUE TITLE
Reach out to API team

### ISSUE THREAD

**Issue by VBeegle** [MobileApps-Cascadia/orca-stars-ios#43]
Def: (Attempt to) contact the API team to see what the current state of the API is, and whether we can use it.
DoD: Sent out messages to API team members

**Comment by charlesmsy** [comment]
Message sent to API team via Slack

**Comment by charlesmsy** [comment]
Web API team responded with GitHub Wiki: https://github.com/Cascadia-Connections/orca-stars/wiki/the-OrcaStars-Web-Application-API

**Comment by charlesmsy** [comment]
No team working on the API FALL2020. API is not online nor capable to conduct CRUD.
